#!/usr/bin/env bash

swaylock \
    --screenshots \
    --clock \
    --indicator \
    --indicator-radius 100 \
    --indicator-thickness 7 \
    --effect-blur 7x5 \
    --effect-vignette 0.5:0.5 \
    --ring-color 61afef \
    --key-hl-color c678dd \
    --line-color 00000000 \
    --inside-color 282c340d \
    --separator-color 00000000 \
    --grace 2 \
    --fade-in 0.2
