[module/backlight]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = amdgpu_bl0
use-actual-brightness = true
enable-scroll = true

format = <ramp> <label>
format-background = ${color.BG}

; Available tokens:
;   %percentage% (default)
label = %percentage%%

; Only applies if <ramp> is used

ramp-0 = " "
ramp-1 = " "
ramp-2 = " "
ramp-3 = " "
ramp-4 = " "
ramp-5 = " "
ramp-6 = " "
ramp-7 = " "
ramp-8 = " "
ramp-9 = " "
ramp-font = 1
ramp-foreground = ${color.CYAN}
