[module/sep]
type = custom/text
content = -

content-background = ${color.BG}
content-foreground = ${color.BG}

[module/dot]
type = custom/text
content = 

content-background = ${color.BG}
content-foreground = ${color.BGL}
content-padding = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/LD]
type = custom/text
content = "%{T3} %{T-}"
content-foreground = ${color.BG}

[module/RD]
type = custom/text
content = "%{T3} %{T-}"
content-foreground = ${color.BG}
