[module/menu]
type = custom/text

content = " "
content-font = 1
;content = " "
;content-font = 3
content-foreground = ${color.BLUE}
content-background = ${color.BG}
content-padding = 0

click-left = ~/.config/rofi/launchers/type-3/launcher.sh
;;click-middle = path_to_script
;;click-right = path_to_script

;;scroll-up = path_to_script
;;scroll-down = path_to_script
