[module/mpd]
type = internal/mpd
interval = 1

format-online = <label-song> <icon-prev> <toggle> <icon-next>
format-online-prefix = " "
format-online-prefix-foreground = ${color.green}
format-online-background = ${color.background}

format-playing = ${self.format-online}
format-paused = ${self.format-online}
format-stopped = ${self.format-online}

format-offline = <label-offline>
format-offline-prefix = 
format-offline-prefix-foreground = ${color.red}
format-offline-background = ${color.background}

label-song =  " %title%"
label-song-maxlen = 25
label-song-ellipsis = true

label-time = %elapsed% / %total%
label-time-background = ${color.background-alt}
label-time-padding = 1

label-offline = " Offline"

icon-play = 
icon-play-foreground = ${color.cyan}
icon-pause = 
icon-pause-foreground = ${color.cyan}
icon-stop = 
icon-stop-foreground = ${color.red}
icon-next = 
icon-next-foreground = ${color.cyan}
icon-prev = 
icon-prev-foreground = ${color.cyan}
icon-seekf =
icon-seekb =
icon-random =
icon-repeat =
icon-repeatone =
icon-single =
icon-consume =

toggle-on-foreground = ${color.primary}
toggle-off-foreground = ${color.red}

; Change it for yourself

[module/wired-network]
type = internal/network
interface = enp2s0

[module/wireless-network]
type = internal/network
interface = wlp3s0

[module/network]
type = internal/network
interface = wlp3s0

interval = 1.0

accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = 
format-connected-prefix-foreground = ${color.orange}
format-connected-background = ${color.background}
format-connected-padding = 0

format-disconnected = <label-disconnected>
format-disconnected-prefix = 
format-disconnected-prefix-foreground = ${color.red}
format-disconnected-background = ${color.background}
format-disconnected-padding = 0

label-connected = "%{A1:networkmanager_dmenu &:} %essid% %downspeed%%{A}"

label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"
