# blur
blur-method = "kawase";
blur-background = true;
blur-background-frame = false;
background-fixed = false;
blur-strength = 1;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'slop'",
    "_GTK_FRAME_EXTENTS@:c"
];

# corners-radius
corner-radius = 18.0;
rounded-corners-exclude = [
    # "window_type = 'normal'",
    "class_g = 'i3bar'",
    "class_g = 'i3-frame'",
    "class_g = 'Polybar'",
    "class_g = 'fcitx'",
];
