;; Global WM Settings

[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL top value
; Used for top aligned bars
margin-bottom = 0

; Adjust the _NET_WM_STRUT_PARTIAL bottom value
; Used for bottom aligned bars
margin-top = 0

fixed-center = true

include-file = $HOME/.config/polybar/include-modules.ini

;; Bar Settings

[bar/main]

modules-left = LD menu dot i3 bspwm RD LD mpd RD LD network RD
modules-center = LD dot date dot RD
modules-right =  LD temperature dot cpu dot memory RD LD backlight dot pulseaudio RD LD battery dot power RD
separator =

monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
wm-name =
locale =

bottom = false
fixed-center = true
padding = 0
width = 100%
height = 31
offset-x = 0%
offset-y = 0%
radius-top = 0
radius-bottom = 0

background = ${color.TRANS}
foreground = ${color.FG}
dim-value = 1.0

line-size = 2
line-color = ${color.BG}

border-top-size = 8
border-top-color = ${color.TRANS}
border-left-size = 8
border-left-color = ${color.TRANS}
border-right-size = 8
border-right-color = ${color.TRANS}

font-0 = "Iosevka Nerd Font:size=12;4"
font-1 = "Iosevka Nerd Font:style=Medium:size=18;4"
font-2 = "feather:size=13;5"

tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = ${color.TRANS}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

;; Application Settings

[settings]
; The throttle settings lets the eventloop swallow up til X events
; if they happen within Y millisecond after first event was received.
; This is done to prevent flood of update event.
;
; For example if 5 modules emit an update event at the same time, we really
; just care about the last one. But if we wait too long for events to swallow
; the bar would appear sluggish so we continue if timeout
; expires or limit is reached.
throttle-output = 5
throttle-output-for = 10
; Time in milliseconds that the input handler will wait between processing events
;throttle-input-for = 30

; Reload upon receiving XCB_RANDR_SCREEN_CHANGE_NOTIFY events
screenchange-reload = true

; Compositing operators
; @see: https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
;format-foreground = 
;format-background = 
;format-underline =
;format-overline =
;format-spacing =
;format-padding =
;format-margin =
;format-offset =

; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;      __________  ______
;;     / ____/ __ \/ ____/
;;    / __/ / / / / /_    
;;   / /___/ /_/ / __/    
;;  /_____/\____/_/       
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
